In [23]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("web_point_row16_bottle86.db")
df = pd.read_sql_query("SELECT * FROM points", conn)
conn.close()

df.to_csv('points_row16_bottle86.db', index=False)
# print(df['name'])

# keep = ['calib_filler_under_approach', 'calib_filler_insert', 'calib_filler_edge',
#        'temp_pointApproach', 'calib_btw_approach', 'calib_temp_grip', 'b86_calib_filler_under_approach', 'b86_calib_filler_insert', 'b86_calib_filler_edge',
#        'b86_temp_pointApproach', 'B86_calib_btw_approach', 'B86_calib_temp_grip']
keep = ['b86_calib_filler_under_approach', 'b86_calib_filler_insert', 'b86_calib_filler_edge',
       'b86_temp_pointApproach', 'B86_calib_btw_approach', 'B86_calib_temp_grip']
# keep = ['calib_filler_insert', 'calib_filler_edge','calib_temp_pointApproach',
#        'temp_pointApproach', 'calib_btw_approach', 'calib_temp_grip'] #,'calib_filler_under_approach']

df = df[df['name'].isin(keep)]
df[['name','x','y','z','rx','ry','rz']]  #'j1','j2','j3','j4','j5','j6',

# df_sorted = df.sort_values('name')
# df_sorted.to_csv('b86_filler.dat', index=False)

,name,x,y,z,rx,ry,rz
36,b86_temp_pointApproach,-75.499,-566.501,204.998,173.867,44.703,114.687
37,B86_calib_btw_approach,-75.501,-566.503,160.001,173.868,44.703,114.687
38,B86_calib_temp_grip,-75.501,-566.504,140.993,173.868,44.704,114.688
39,b86_calib_filler_under_approach,-39.001,-513.002,209.998,173.863,44.704,114.684
40,b86_calib_filler_insert,-39.499,-513.002,330.505,173.865,44.706,114.684
41,b86_calib_filler_edge,-39.499,-513.005,310.001,173.864,44.707,114.683

In [ ]:
-- Spacing between bottles (mm) this will no longer be necessary!!!!
  spacing = {
    d_x = 58,       -- between bottles
    d_y = 1.5,
    d_x_last = 29,  -- end of row correction
    d_y_last = 16,  -- end of row correction (y)
  },

In [1]:
import pandas as pd

In [4]:
data = pd.read_csv('b86_filler.dat')

In [6]:
data.columns

Index(['name', 'speed', 'elbow_speed', 'acc', 'elbow_acc', 'toolnum',
       'workpiecenum', 'j1', 'j2', 'j3', 'j4', 'j5', 'j6', 'E1', 'E2', 'E3',
       'E4', 'x', 'y', 'z', 'rx', 'ry', 'rz'],
      dtype='object')

In [7]:
data[['name','j1','j2','j3','j4','j5','j6','x','y','z','rx','ry','rz']]

,name,j1,j2,j3,j4,j5,j6,x,y,z,rx,ry,rz
0,b86_calib_filler_edge,67.376,-67.830,84.587,43.995,54.086,-130.165,-39.499,-513.005,310.001,173.864,44.707,114.683
1,b86_calib_filler_insert,67.376,-68.568,82.547,46.774,54.087,-130.166,-39.499,-513.002,330.505,173.865,44.706,114.684
2,b86_calib_filler_under_approach,67.435,-62.492,92.444,30.766,54.116,-130.104,-39.001,-513.002,209.998,173.863,44.704,114.684